export const COLOR_LIST = [
  { name: "MDF, 한솔, 18T, 크림화이트", image: "/img/color-list/hansol-cream-white.png" },
  { name: "MDF, 한솔, 18T, 퍼펙트화이트", image: "/img/color-list/hansol-perfect-white.png" },
  { name: "MDF, 한솔, 18T, 도브화이트", image: "/img/color-list/hansol-dove-white.png" },
  { name: "MDF, 한솔, 18T, 포그그레이", image: "/img/color-list/hansol-fog-gray.png" },
  { name: "MDF, 한솔, 18T, 샌드그레이", image: "/img/color-list/hansol-sand-gray.png" },
  { name: "MDF, 한솔, 18T, 테네시월넛", image: "/img/color-list/hansol-tennessee-walnut.png" },
  { name: "MDF, 한솔, 18T, 베이내츄럴오크", image: "/img/color-list/hansol-bay-natural-oak.png" },
  { name: "MDF, 한솔, 18T, 내츄럴크랙오크", image: "/img/color-list/hansol-natural-crack-oak.png" },
  { name: "MDF, 한솔, 18T, 칼프브라운", image: "/img/color-list/hansol-calf-brown.png" },
  // { name: "MDF, 한솔, 18T, 칼프브라운우드", image: "/img/color-list/hansol-calp-brown-wood.png" },
  { name: "MDF, 한솔, 18T, 콘크리트샌드", image: "/img/color-list/hansol-concrete-sand.png" },
  { name: "MDF, 한솔, 18T, 콘크리트화이트", image: "/img/color-list/hansol-concrete-white.png" },
  { name: "MDF, 한솔, 18T, 새틴베이지", image: "/img/color-list/hansol-satin-beige.png" },
  { name: "MDF, 한솔, 18T, 코튼블루", image: "/img/color-list/hansol-cotton-blue.png" },
  { name: "PB, 한솔, 18T, 파타고니아크림", image: "/img/color-list/hansol-patagonia-cream.png" },
  // {
  //   name: "MDF, 기타, 18T, 연아이보리 무광",
  //   image: "/img/color-list/hansol-light-ivory-matte.png",
  // },
  { name: "MDF, 동화, 18T, 밀크화이트", image: "/img/color-list/dongwha-milk-white.png" },
  { name: "MDF, 동화, 18T, 카본그레이", image: "/img/color-list/dongwha-carbon-gray.png" },
  { name: "PB,, 18T, 헤링본", image: "/img/color-list/herringbone.png" },
  { name: "PB,, 15T, 헤링본", image: "/img/color-list/herringbone.png" },
  { name: "PB, 동화, 3T 우라, 헤링본", image: "/img/color-list/herringbone.png" },
  { name: "PB,, 15T, 헤링본 - 미백색", image: "/img/color-list/herringbone-off-white.png" },
] as const;
